/*
SQLyog Trial v13.1.9 (64 bit)
MySQL - 8.4.5 : Database - adele_sistem
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*Table structure for table `t_insurance_bundling` */

DROP TABLE IF EXISTS `t_insurance_bundling`;

CREATE TABLE `t_insurance_bundling` (
  `INSURANCE_BUNDLING_ID` int NOT NULL AUTO_INCREMENT,
  `INSURANCE_ID` int DEFAULT NULL,
  `INSURANCE_BUNDLING` int DEFAULT NULL,
  `INSURANCE_BUNDLING_LEADER` int DEFAULT NULL,
  `INSURANCE_BUNDLING_CREATED_BY` int DEFAULT NULL,
  `INSURANCE_BUNDLING_UPDATED_BY` datetime DEFAULT NULL,
  PRIMARY KEY (`INSURANCE_BUNDLING_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
