/*
SQLyog Trial v13.1.9 (64 bit)
MySQL - 5.7.36 : Database - adele_master
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*Table structure for table `t_insurance` */

DROP TABLE IF EXISTS `t_insurance`;

CREATE TABLE `t_insurance` (
  `INSURANCE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `INSURANCE_NAME` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `INSURANCE_CODE` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `INSURANCE_SLUG` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `INSURANCE_LOGO` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `INSURANCE_NOTE` text COLLATE utf8mb4_unicode_ci,
  `INSURANCE_CREATED_BY` int(11) DEFAULT NULL,
  `INSURANCE_CREATED_DATE` datetime DEFAULT NULL,
  `INSURANCE_UPDATED_BY` int(11) DEFAULT NULL,
  `INSURANCE_UPDATED_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`INSURANCE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Data for the table `t_insurance` */

insert  into `t_insurance`(`INSURANCE_ID`,`INSURANCE_NAME`,`INSURANCE_CODE`,`INSURANCE_SLUG`,`INSURANCE_LOGO`,`INSURANCE_NOTE`,`INSURANCE_CREATED_BY`,`INSURANCE_CREATED_DATE`,`INSURANCE_UPDATED_BY`,`INSURANCE_UPDATED_DATE`) values 
(1,'CHUBB','001','chubb','15',NULL,NULL,NULL,95,'2025-03-18 16:05:13'),
(2,'HEKSA','002','heksa','20',NULL,NULL,NULL,95,'2025-03-18 15:05:39'),
(3,'Jamkirda Jabar','003','jamkirda-jabar','21',NULL,95,'2025-03-15 13:27:57',95,'2025-03-18 16:05:29');

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
