/*
SQLyog Trial v13.1.9 (64 bit)
MySQL - 5.7.36 : Database - adele_new_source
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*Table structure for table `r_marital_status` */

DROP TABLE IF EXISTS `r_marital_status`;

CREATE TABLE `r_marital_status` (
  `MARITAL_STATUS_ID` int(8) NOT NULL AUTO_INCREMENT,
  `MARITAL_STATUS_SELECT` int(8) DEFAULT NULL,
  `MARITAL_STATUS_NAME` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `MARITAL_STATUS_CREATED_BY` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `MARITAL_STATUS_CREATED_DATE` datetime DEFAULT NULL,
  `MARITAL_STATUS_UPDATED_BY` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `MARITAL_STATUS_UPDATED_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`MARITAL_STATUS_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Data for the table `r_marital_status` */

insert  into `r_marital_status`(`MARITAL_STATUS_ID`,`MARITAL_STATUS_SELECT`,`MARITAL_STATUS_NAME`,`MARITAL_STATUS_CREATED_BY`,`MARITAL_STATUS_CREATED_DATE`,`MARITAL_STATUS_UPDATED_BY`,`MARITAL_STATUS_UPDATED_DATE`) values 
(1,0,'Single',NULL,NULL,NULL,NULL),
(2,1,'Menikah dan Mempunyai Anak',NULL,NULL,NULL,NULL),
(3,2,'Janda / Duda dan Mempunyai Anak',NULL,NULL,NULL,NULL),
(4,3,'Janda / Duda dan Tanpa Mempunyai Anak',NULL,NULL,NULL,NULL);

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
